name: Mention Contributor and Reviewer
description: 'This action mention the contributor and reviewer for a pull request.'
    
outputs:
  contributorID:
    description: "Slack ID of contributor"
    value: ${{ steps.get-contributor-slack.outputs.contributorID }}
  reviewerID:
    description: "Slack ID of reviewer"
    value: ${{ steps.get-reviewer-slack.outputs.reviewerID }}
  reviewer:
    description: "Reviewer of PIC iOS"
    value: ${{ steps.get-reviewer.outputs.reviewer }}
  send-slack-notification:
    description: "Send Slack notification"
    value: ${{ steps.send-slack-notification}}
    
runs:
  using: "composite"
  steps:
    - name: Get slack ID of contributor
      shell: bash
      id: get-contributor-slack
      run: |
        contributorID=$(echo "$(cat ./.github/test.json)" | jq '.contributor["${{ github.event.pull_request.user.login }}"]')
        echo "::set-output name=contributorID::${contributorID}"
    
    - name: Get reviewer of PIC iOS
      shell: bash
      id: get-reviewer
      run: |
        reviewer=$(echo "$(cat $GITHUB_EVENT_PATH)" | jq -r '.pull_request.requested_reviewers[] | select(.login | contains("ko")) | {login} | join(" ")')
        echo "::set-output name=reviewer::${reviewer}"

    - name: Get slack ID of reviewer
      shell: bash
      id: get-reviewer-slack
      run: |
        reviewerID=$(echo "$(cat ./.github/test.json)" | jq '.reviewer["${{ steps.get-reviewer.outputs.reviewer }}"]')
        echo "::set-output name=reviewerID::${reviewerID}"
        
    - name: Send slack notification
      shell: bash
      id: send-slack-notification
      run: |
        if test -z "$SLACK_BOT_TOKEN"; then
            echo "Set the SLACK_BOT_TOKEN secret."
            exit 1
        fi
        curl -X POST \
             -H "Content-type: application/json" \
             -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
             -d "$*" \
             https://slack.com/api/chat.postMessage
