# This is a basic workflow to help you get started with Actions

name: Slack Notifications
description: 'This action creates a string that mentions all the reviewers for a pull request.'
branding:
  icon: 'users'  
  color: 'blue'
    
outputs:
  slackid:
    description: "Slack of committed person"
    value: ${{ steps.committed-slack-generator.outputs.slackid }}
  reviewer:
    description: "Reviewer of committed person"
    value: ${{ steps.reviewer-generator.outputs.reviewer }}
    
runs:
  using: "composite"
  steps:
    - name: Check slack of committed person
      shell: bash
      id: committed-slack-generator
      run: |
        slackid=$(echo "$(cat ./.github/test.json)" | jq '.${{ github.event.pull_request.user.login }}["id"]')
        echo "::set-output name=slackid::${slackid}"
        
    - name: Check reviewer of committed person
      shell: bash
      id: reviewer-generator
      run: |
        reviewer=$(echo "$(cat ./.github/test.json)" | jq '.${{ github.event.pull_request.user.login }}["reviewerID"]')
        echo "::set-output name=reviewer::${reviewer}"
