name: Mention Contributor and Reviewer
description: 'This action mention the contributor and reviewer for a pull request.'
    
outputs:
  contributorID:
    description: "Slack ID of contributor"
    value: ${{ steps.get-contributor-slack.outputs.contributorID }}
  reviewerID:
    description: "Reviewer of PIC iOS"
    value: ${{ steps.get-reviewer.outputs.reviewerID }}
    
runs:
  using: "composite"
  steps:
    - name: Get slack ID of contributor
      shell: bash
      id: get-contributor-slack
      run: |
        contributorID=$(echo "$(cat ./.github/test.json)" | jq '.contributor["${{ github.event.pull_request.user.login }}"]')
        echo "::set-output name=contributorID::${contributorID}"
    
    - name: Get reviewer of PIC iOS
      shell: bash
      id: get-reviewer
      run: |
        export reviewer=$(echo "$(cat $GITHUB_EVENT_PATH)" | jq -r '.pull_request.requested_reviewers[] | select(.login | contains("ko")) | {login} | join(" ")')
        echo "outputnya: $reviewer" 
        reviewerID=$(echo "$(cat ./.github/test.json)" | jq '.reviewer[$reviewer]')
        echo "reviewerID: $reviewerID" 
        echo "::set-output name=reviewerID::${reviewerID}"
