name: Mention Contributor and Reviewer
description: 'This action mention the contributor and reviewer for a pull request.'
    
outputs:
  contributorID:
    description: "Slack ID of contributor"
    value: ${{ steps.get-contributor-slack.outputs.contributorID }}
  reviewerID:
    description: "Slack ID of reviewer"
    value: ${{ steps.get-reviewer-slack.outputs.reviewerID }}
  reviewer:
    description: "Reviewer of PIC iOS"
    value: ${{ steps.get-reviewer.outputs.reviewer }}
  send-slack-notification:
    description: "Send Slack notification"
    value: ${{ steps.send-slack-notification}}
    
runs:
  using: "composite"
  steps:
    - name: Get slack ID of contributor
      shell: bash
      id: get-contributor-slack
      run: |
        contributorID=$(echo "$(cat ./.github/test.json)" | jq '.contributor["${{ github.event.pull_request.user.login }}"]')
        echo "::set-output name=contributorID::${contributorID}"
    
    - name: Get reviewer of PIC iOS
      shell: bash
      id: get-reviewer
      run: |
        reviewer=$(echo "$(cat $GITHUB_EVENT_PATH)" | jq -r '.pull_request.requested_reviewers[] | select(.login | contains("ko")) | {login} | join(" ")')
        echo "::set-output name=reviewer::${reviewer}"

    - name: Get slack ID of reviewer
      shell: bash
      id: get-reviewer-slack
      run: |
        reviewerID=$(echo "$(cat ./.github/test.json)" | jq '.reviewer["${{ steps.get-reviewer.outputs.reviewer }}"]')
        echo "::set-output name=reviewerID::${reviewerID}"
        
    - name: Send slack notification
      shell: bash
      id: send-slack-notification
      run: |
        curl -X POST -H 'Authorization: Bearer $SLACK_BOT_TOKEN' \
            -H 'Content-type: application/json; charset=utf-8' \
            --data '{"channel":"C02LV4R4X4Z","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"${{ github.event.pull_request.title }} <@${{ steps.get-contributor-slack.outputs.contributorID }}>"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Reviewer*"},{"type":"mrkdwn","text":"<@${{ steps.get-reviewer-slack.outputs.reviewerID }}>"},{"type":"mrkdwn","text":"*Status*"},{"type":"mrkdwn","text":"`Need Approval`"}]},{"type":"section","text":{"type":"mrkdwn","text":"<${{ github.event.pull_request.html_url }} | View Pull Request>"}}]}' \
            https://slack.com/api/chat.postMessage
