# This is a basic workflow to help you get started with Actions

name: Mention Contributor and Reviewer
description: 'This action mention the contributor and reviewer for a pull request.'
    
outputs:
  contributorID:
    description: "Slack ID of contributor"
    value: ${{ steps.get-contributor-slack.outputs.contributorID }}
  reviewerID:
    description: "Slack ID of reviewer"
    value: ${{ steps.get-reviewer-slack.outputs.reviewerID }}
  reviewer:
    description: "Slack ID of reviewer"
    value: ${{ steps.get-reviewer.outputs.reviewer }}
    
runs:
  using: "composite"
  steps:
    - name: Get slack ID of contributor
      shell: bash
      id: get-contributor-slack
      run: |
        contributorID=$(echo "$(cat ./.github/test.json)" | jq '.${{ github.event.pull_request.user.login }}["id"]')
        echo "::set-output name=contributorID::${contributorID}"
        
    - name: Get slack ID of reviewer
      shell: bash
      id: get-reviewer-slack
      run: |
        reviewerID=$(echo "$(cat ./.github/test.json)" | jq '.${{ github.event.pull_request.user.login }}["reviewerID"]')
        echo "::set-output name=reviewerID::${reviewerID}"
    
    - name: Get reviewer
      shell: bash
      id: get-reviewer
      run: |
        reviewer=$(echo "$(cat $GITHUB_EVENT_PATH)" | jq '.pull_request.requested_reviewers | map("@" + .login)')
        echo "::set-output name=reviewer::${reviewer}"
