name: Mention Contributor and Reviewer
description: 'This action mention the contributor and reviewer for a pull request.'
    
outputs:
  contributorID:
    description: "Slack ID of contributor"
    value: ${{ steps.get-contributor-slack.outputs.contributorID }}
  reviewerIOS:
    description: "Reviewer of PIC iOS"
    value: ${{ steps.get-reviewer.outputs.reviewerIOS }}
  reviewerID:
    description: "Slack ID of reviewer"
    value: ${{ steps.get-reviewer-slack.outputs.reviewerID }}
    
runs:
  using: "composite"
  steps:
    - name: Get slack ID of contributor
      shell: bash
      id: get-contributor-slack
      run: |
        contributorID=$(echo "$(cat ./.github/test.json)" | jq '.contributor["${{ github.event.pull_request.user.login }}"]')
        echo "::set-output name=contributorID::${contributorID}"
    
    - name: Get reviewer of PIC iOS only
      shell: bash
      id: get-reviewer
      run: |
        reviewerIOS=$(echo "$(cat $GITHUB_EVENT_PATH)" | jq -r '.pull_request.requested_reviewers[] | select(.login | contains("ko") | {login} | join(" ")')
        echo "::set-output name=reviewerIOS::${reviewerIOS}"

    - name: Get slack ID of reviewer
      shell: bash
      id: get-reviewer-slack
      run: |
        reviewerID=$(echo "$(cat ./.github/test.json)" | jq '.reviewer["${{ steps.get-reviewer.outputs.reviewerIOS }}"]')
        echo "::set-output name=reviewerID::${reviewerID}"
