# This is a basic workflow to help you get started with Actions

name: Slack Notifications
description: 'This action creates a string that mentions all the reviewers for a pull request.'
branding:
  icon: 'users'  
  color: 'blue'
    
outputs:
  slackid:
    description: "Slack of committed person"
    value: ${{ steps.committed-slack-generator.outputs.slackid }}
    
runs:
  using: "composite"
  steps:
    - name: Check slack of committed person
      shell: bash
      id: committed-slack-generator
      run: |
        slackid=$(echo "$(cat test.json)" | jq '.test')
        echo "::set-output name=slackid::${slackid}"
