# This is a basic workflow to help you get started with Actions

name: Slack Notifications
description: 'This action creates a string that mentions all the reviewers for a pull request.'
branding:
  icon: 'users'  
  color: 'blue'

inputs:
  slack-oauth-token: ${{ secrets.SLACK_WEBHOOK_URL }}
    description: 'Slack token for users mention'
    
outputs:
  git-email:
    description: "Email of committed person"
    value: ${{ steps.committed-email-generator.outputs.email }}
  slack-username:
    description: "Slack username of committed person"
    value: ${{ steps.slack-username-generator.outputs.userID }}
    
runs:
  using: "composite"
  steps:
    - name: Check email of committed person
      shell: bash
      id: committed-email-generator
      run: |
        email=$(git log -1 --pretty=format:"%ce" $GITHUB_SHA)
        echo "::set-output name=email::${email}"

    - name: Check slack username with email
      shell: bash
      id: slack-username-generator
      run: |
        userID=$(curl -s --no-progress-meter "https://slack.com/api/users.lookupByEmail?token=${{ inputs.slack-oauth-token }}&email=${{ steps.committed-email-generator.outputs.email }}" | jq -r '.user.id')
        echo "::set-output name=userID::${userID}"
