name: Need Approval Notification

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  notifySlack:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automation') && contains(github.event.pull_request.labels.*.name, 'need-approval')
    steps:
      - uses: actions/checkout@v2
      - name: Extract contributor ID info
        uses: ./.github
        id: get-contributor-slack
        
      - name: Extract reviewer ID info
        uses: ./.github
        id: get-reviewer-slack
        
      - name: Extract reviewer info
        uses: ./.github
        id: get-reviewer
        
      - name: Send notification to contributor and reviewer
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#           PR_title: ${{ github.event.pull_request.title }}
#           PR_link: ${{ github.event.pull_request.html_url }}
        uses: ./.github
        id: send-slack-notification
