name: Need Approval Notification

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  notifySlack:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automation') && contains(github.event.pull_request.labels.*.name, 'need-approval')
    steps:
      - uses: actions/checkout@v2
      - name: Extract contributor ID slack
        uses: ./.github
        id: get-contributor-slack
        
      - name: Extract reviewer info
        uses: ./.github
        id: get-reviewer
        
      - name: Extract reviewer ID slack
        uses: ./.github
        id: get-reviewer-slack
        
      - name: Send Slack notification
        uses: ./.github
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          pr_title: ${{ github.event.pull_request.title }}
          contributor: ${{ steps.get-contributor-slack.outputs.contributorID }}
          reviewer: ${{ steps.get-reviewer-slack.outputs.reviewerID }}
          link: ${{ github.event.pull_request.html_url }}
        id: notif
#         with:
#           args: '{\"channel\":\"C02LV4R4X4Z\",\"blocks\": [{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${{ github.event.pull_request.title }} <@${{ steps.get-contributor-slack.outputs.contributorID }}>\"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Reviewer*\"},{\"type\":\"mrkdwn\",\"text\":\"<@${{ steps.get-reviewer-slack.outputs.reviewerID }}>\"},{\"type\":\"mrkdwn\",\"text\":\"*Status*\"},{\"type\":\"mrkdwn\",\"text\":\"`Need Approval`\"}]},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }} | View Pull Request>\"}}]}'
