name: PR Approval Notification

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  notifySlack:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automation')
    steps:
      - uses: actions/checkout@v2
      - name: Extract contributor ID slack
        id: get-contributor-slack
        run: |
          contributorID=$(echo "$(cat ./.github/test.json)" | jq '.contributor["${{ github.event.pull_request.user.login }}"]' | tr -d \")
          if [ contributorID == null ]
          then
            contributorID="unknown"
          fi
          echo "::set-output name=contributorID::${contributorID}"
        
      - name: Extract reviewer ID slack
        id: get-reviewer-slack
        run: |
          export reviewerIOS=$(echo "$(cat $GITHUB_EVENT_PATH)" | jq -r '.pull_request.requested_reviewers[] | ["snarizky", "test", "123"] as $pic | select(.login as $username | any ($pic[]; . == $username)) | {login} | join(" ")')
          reviewerID=$(echo "$(cat ./.github/test.json)" | jq '.reviewer["'$reviewerIOS'"]' | tr -d \")
          echo "::set-output name=reviewerID::${reviewerID}"
        
      - name: Send Slack notification
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_LINK: ${{ github.event.pull_request.html_url }} 
          CONTRIBUTOR_ID: ${{ steps.get-contributor-slack.outputs.contributorID }}
          REVIEWER_ID: ${{ steps.get-reviewer-slack.outputs.reviewerID }}
        run: |
          data='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"'$PR_TITLE' <@'$CONTRIBUTOR_ID'>"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Reviewer*"},{"type":"mrkdwn","text":"<@'$REVIEWER_ID'>"},{"type":"mrkdwn","text":"*Status*"},{"type":"mrkdwn","text":"`Need Approval`"}]},{"type":"section","text":{"type":"mrkdwn","text":"<'$PR_LINK' | View Pull Request>"}}]}'
          curl -X POST \
               -H "Content-type: application/json" \
               -d "$data" \
               https://hooks.slack.com/services/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
