# This is a basic workflow to help you get started with Actions

name: Need Approval Notification

on:
  pull_request:
    types: [ labeled ]
    
jobs:
  notifySlack:
    runs-on: ubuntu-latest
#     if: ${{ github.event.label.name == 'automation' }} && {{ github.event.label.name == 'need-approval' }}
    if: contains(github.event.pull_request.labels.*.name, 'automation')
    steps:
      - uses: actions/checkout@v2
      - name: Extract contributor ID info
        uses: ./.github
        id: get-contributor-slack
        
      - name: Extract reviewer ID info
        uses: ./.github
        id: get-reviewer-slack
        
      - name: Extract reviewer info
        uses: ./.github
        id: get-reviewer
        
      - name: Send notification to contributor and reviewer
        uses: pullreminders/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"C02LV4R4X4Z\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${{ github.event.pull_request.title }} <@${{ steps.get-contributor-slack.outputs.contributorID }}>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Reviewer:* <@${{ steps.get-reviewer-slack.outputs.reviewerID }}>\n*Status:* `Need Approval`\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'
